Refactor root component
reimagined/hacker-news-resolve pull request #30
Opened 2017-09-12 14:38 UTC by Vasiliy-Lavrov

2017-09-12 14:39 UTC, MrCheater approved these changes

2017-09-12 14:39 UTC, MrCheater approved these changes

2017-09-12 14:40 UTC, kilimondjaro approved these changes

2017-09-13 06:20 UTC, timbset requested changes

2017-09-13 06:20 UTC, timbset commented on client/components/App.js
> +export const serverRootComponent = (props, context) => (
The `context` param is unused

2017-09-13 06:27 UTC, Vasiliy-Lavrov commented on client/components/App.js
> +export const serverRootComponent = (props, context) => (
fixed

2017-09-13 06:27 UTC, timbset approved these changes

2017-09-13 06:50 UTC, merged