Refactoring/users
reimagined/hacker-news-resolve pull request #38
Opened 2017-09-18 13:19 UTC by MrCheater

2017-09-18 14:00 UTC, xv2 approved these changes

2017-09-18 14:04 UTC, timbset requested changes

2017-09-18 14:04 UTC, timbset commented on server/index.js
> +      )).users
Too many braces. But the 'await' result to other const.

2017-09-18 14:04 UTC, timbset commented on server/index.js
> +      )).users
The same one

2017-09-18 14:04 UTC, timbset commented on server/index.js
> +    )).users
And here

2017-09-19 11:25 UTC, timbset approved these changes

2017-09-19 11:28 UTC, merged