Fix flow
reimagined/hacker-news-resolve pull request #67
Opened 2017-10-12 08:35 UTC by Vasiliy-Lavrov

2017-10-12 09:12 UTC, timbset requested changes

2017-10-12 09:12 UTC, timbset commented on common/read-models/comments.js
> +}>
First. Extract inner type as a Comment. 
Second. Where is it used?

2017-10-12 09:12 UTC, timbset commented on common/read-models/stories.js
> +}>
The same

2017-10-12 09:12 UTC, timbset commented on common/read-models/users.js
> +}>
And here

2017-10-12 09:12 UTC, timbset commented on flow-typed/events.js
> +}>
And in this file

2017-10-12 09:27 UTC, MrCheater approved these changes

2017-10-12 10:36 UTC, kilimondjaro approved these changes

2017-10-13 08:47 UTC, MrCheater approved these changes

2017-10-13 08:49 UTC, timbset approved these changes

2017-10-13 08:58 UTC, kilimondjaro approved these changes

2017-10-13 08:58 UTC, merged